name: Publish Beta

on:
  push:
    branches: [beta]

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: nelonoel/branch-name@v1
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Test
        id: install
        run: |
          npm install  
          npm test
      - name: Publish
        id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: "${BRANCH_NAME}"
          dry-run: true
      - name: Git Release
        if: steps.publish.outputs.type != 'none'
        uses: "marvinpinto/action-automatic-releases@v1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${BRANCH_NAME}"
          title: "${{ steps.publish.outputs.version }}"
          prerelease: true
          draft: true
