name: Publish Beta

on:
  push:
    branches: [beta]

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        id: getBranchName
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Test
        id: install
        run: |
          npm install  
          npm test
      - name: Publish
        id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: "${{ steps.getBranchName.outputs.branch}}"
          dry-run: true
      - name: Git Release
        if: steps.publish.outputs.type != 'none'
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.getBranchName.outputs.branch}}"
          title: "${{ steps.publish.outputs.version }}"
          prerelease: true
          draft: true
